// @generated by scripts/generate_payloads.py — do not edit by hand.
#pragma once

#include <map>
#include <string>

#include <nlohmann/json.hpp>

namespace airbus {
namespace contracts {

struct MethodInfo {
  std::string params;  // schema filename, empty if none
  bool params_required = false;
  std::string result;
  std::string receiver;
};

const std::map<std::string, nlohmann::json>& schemas();
const std::map<std::string, MethodInfo>& methods();

}  // namespace contracts
}  // namespace airbus
