// @generated by scripts/generate_payloads.py — do not edit by hand.
// Source of truth: schema/payloads/*.schema.json
#pragma once

#include <cstdint>
#include <optional>
#include <stdexcept>
#include <string>
#include <vector>

#include <nlohmann/json.hpp>

namespace airbus {

using PingResult = std::string;
using AddResult = double;
using AddParams = std::vector<double>;

enum class QueueMode {
  Broadcast,
  Fifo,
  FullDuplex,
};

inline void to_json(nlohmann::json& j, QueueMode value) {
  switch (value) {
    case QueueMode::Broadcast: j = "broadcast"; break;
    case QueueMode::Fifo: j = "fifo"; break;
    case QueueMode::FullDuplex: j = "full-duplex"; break;
  }
}

inline void from_json(const nlohmann::json& j, QueueMode& value) {
  const auto& s = j.get_ref<const std::string&>();
  if (s == "broadcast") { value = QueueMode::Broadcast; return; }
  if (s == "fifo") { value = QueueMode::Fifo; return; }
  if (s == "full-duplex") { value = QueueMode::FullDuplex; return; }
  throw std::invalid_argument("invalid QueueMode: " + s);
}

enum class DispatchStrategy {
  RoundRobin,
  SingleNode,
};

inline void to_json(nlohmann::json& j, DispatchStrategy value) {
  switch (value) {
    case DispatchStrategy::RoundRobin: j = "round_robin"; break;
    case DispatchStrategy::SingleNode: j = "single_node"; break;
  }
}

inline void from_json(const nlohmann::json& j, DispatchStrategy& value) {
  const auto& s = j.get_ref<const std::string&>();
  if (s == "round_robin") { value = DispatchStrategy::RoundRobin; return; }
  if (s == "single_node") { value = DispatchStrategy::SingleNode; return; }
  throw std::invalid_argument("invalid DispatchStrategy: " + s);
}

enum class DuplexSide {
  Host,
  Device,
};

inline void to_json(nlohmann::json& j, DuplexSide value) {
  switch (value) {
    case DuplexSide::Host: j = "host"; break;
    case DuplexSide::Device: j = "device"; break;
  }
}

inline void from_json(const nlohmann::json& j, DuplexSide& value) {
  const auto& s = j.get_ref<const std::string&>();
  if (s == "host") { value = DuplexSide::Host; return; }
  if (s == "device") { value = DuplexSide::Device; return; }
  throw std::invalid_argument("invalid DuplexSide: " + s);
}

enum class Status {
  Ok,
};

inline void to_json(nlohmann::json& j, Status value) {
  switch (value) {
    case Status::Ok: j = "ok"; break;
  }
}

inline void from_json(const nlohmann::json& j, Status& value) {
  const auto& s = j.get_ref<const std::string&>();
  if (s == "ok") { value = Status::Ok; return; }
  throw std::invalid_argument("invalid Status: " + s);
}

struct QueueInfo {
  std::string name{};
  std::int64_t depth{};
  QueueMode mode{};
  std::int64_t listener_count{};
};

inline void to_json(nlohmann::json& j, const QueueInfo& value) {
  j = nlohmann::json::object();
  j["name"] = value.name;
  j["depth"] = value.depth;
  j["mode"] = value.mode;
  j["listener_count"] = value.listener_count;
}

inline void from_json(const nlohmann::json& j, QueueInfo& value) {
  j.at("name").get_to(value.name);
  j.at("depth").get_to(value.depth);
  j.at("mode").get_to(value.mode);
  j.at("listener_count").get_to(value.listener_count);
}

struct Event {
  std::string id{};
  nlohmann::json event{};
};

inline void to_json(nlohmann::json& j, const Event& value) {
  j = nlohmann::json::object();
  j["id"] = value.id;
  j["event"] = value.event;
}

inline void from_json(const nlohmann::json& j, Event& value) {
  j.at("id").get_to(value.id);
  j.at("event").get_to(value.event);
}

struct Listener {
  std::string id{};
  std::string queue{};
  std::string host{};
  std::int64_t port{};
  QueueMode mode{};
  std::int64_t failure_count{};
  bool active{};
  std::optional<DuplexSide> side{};
};

inline void to_json(nlohmann::json& j, const Listener& value) {
  j = nlohmann::json::object();
  j["id"] = value.id;
  j["queue"] = value.queue;
  j["host"] = value.host;
  j["port"] = value.port;
  j["mode"] = value.mode;
  j["failure_count"] = value.failure_count;
  j["active"] = value.active;
  if (value.side.has_value()) j["side"] = *value.side;
}

inline void from_json(const nlohmann::json& j, Listener& value) {
  j.at("id").get_to(value.id);
  j.at("queue").get_to(value.queue);
  j.at("host").get_to(value.host);
  j.at("port").get_to(value.port);
  j.at("mode").get_to(value.mode);
  j.at("failure_count").get_to(value.failure_count);
  j.at("active").get_to(value.active);
  if (j.contains("side") && !j["side"].is_null()) {
    value.side = j.at("side").get<DuplexSide>();
  } else {
    value.side = std::nullopt;
  }
}

struct PostEventParams {
  std::string queue{};
  nlohmann::json event{};
  std::optional<DuplexSide> side{};
};

inline void to_json(nlohmann::json& j, const PostEventParams& value) {
  j = nlohmann::json::object();
  j["queue"] = value.queue;
  j["event"] = value.event;
  if (value.side.has_value()) j["side"] = *value.side;
}

inline void from_json(const nlohmann::json& j, PostEventParams& value) {
  j.at("queue").get_to(value.queue);
  j.at("event").get_to(value.event);
  if (j.contains("side") && !j["side"].is_null()) {
    value.side = j.at("side").get<DuplexSide>();
  } else {
    value.side = std::nullopt;
  }
}

struct PostEventResult {
  std::string id{};
  std::string queue{};
};

inline void to_json(nlohmann::json& j, const PostEventResult& value) {
  j = nlohmann::json::object();
  j["id"] = value.id;
  j["queue"] = value.queue;
}

inline void from_json(const nlohmann::json& j, PostEventResult& value) {
  j.at("id").get_to(value.id);
  j.at("queue").get_to(value.queue);
}

struct ListQueuesResult {
  std::vector<QueueInfo> queues{};
};

inline void to_json(nlohmann::json& j, const ListQueuesResult& value) {
  j = nlohmann::json::object();
  j["queues"] = value.queues;
}

inline void from_json(const nlohmann::json& j, ListQueuesResult& value) {
  j.at("queues").get_to(value.queues);
}

struct PeekEventsParams {
  std::string queue{};
  std::optional<std::int64_t> count{};
};

inline void to_json(nlohmann::json& j, const PeekEventsParams& value) {
  j = nlohmann::json::object();
  j["queue"] = value.queue;
  if (value.count.has_value()) j["count"] = *value.count;
}

inline void from_json(const nlohmann::json& j, PeekEventsParams& value) {
  j.at("queue").get_to(value.queue);
  if (j.contains("count") && !j["count"].is_null()) {
    value.count = j.at("count").get<std::int64_t>();
  } else {
    value.count = std::nullopt;
  }
}

struct PeekEventsResult {
  std::string queue{};
  std::vector<Event> events{};
};

inline void to_json(nlohmann::json& j, const PeekEventsResult& value) {
  j = nlohmann::json::object();
  j["queue"] = value.queue;
  j["events"] = value.events;
}

inline void from_json(const nlohmann::json& j, PeekEventsResult& value) {
  j.at("queue").get_to(value.queue);
  j.at("events").get_to(value.events);
}

struct CreateQueueParams {
  std::string queue{};
  std::optional<QueueMode> mode{};
  std::optional<DispatchStrategy> dispatch_strategy{};
};

inline void to_json(nlohmann::json& j, const CreateQueueParams& value) {
  j = nlohmann::json::object();
  j["queue"] = value.queue;
  if (value.mode.has_value()) j["mode"] = *value.mode;
  if (value.dispatch_strategy.has_value()) j["dispatch_strategy"] = *value.dispatch_strategy;
}

inline void from_json(const nlohmann::json& j, CreateQueueParams& value) {
  j.at("queue").get_to(value.queue);
  if (j.contains("mode") && !j["mode"].is_null()) {
    value.mode = j.at("mode").get<QueueMode>();
  } else {
    value.mode = std::nullopt;
  }
  if (j.contains("dispatch_strategy") && !j["dispatch_strategy"].is_null()) {
    value.dispatch_strategy = j.at("dispatch_strategy").get<DispatchStrategy>();
  } else {
    value.dispatch_strategy = std::nullopt;
  }
}

struct CreateQueueResult {
  std::string queue{};
  QueueMode mode{};
  bool created{};
};

inline void to_json(nlohmann::json& j, const CreateQueueResult& value) {
  j = nlohmann::json::object();
  j["queue"] = value.queue;
  j["mode"] = value.mode;
  j["created"] = value.created;
}

inline void from_json(const nlohmann::json& j, CreateQueueResult& value) {
  j.at("queue").get_to(value.queue);
  j.at("mode").get_to(value.mode);
  j.at("created").get_to(value.created);
}

struct AttachListenerParams {
  std::string queue{};
  std::int64_t port{};
  std::optional<std::string> host{};
  std::optional<std::int64_t> exhaustion_timeout_ms{};
  std::optional<std::int64_t> max_retries{};
  std::optional<DuplexSide> side{};
};

inline void to_json(nlohmann::json& j, const AttachListenerParams& value) {
  j = nlohmann::json::object();
  j["queue"] = value.queue;
  j["port"] = value.port;
  if (value.host.has_value()) j["host"] = *value.host;
  if (value.exhaustion_timeout_ms.has_value()) j["exhaustion_timeout_ms"] = *value.exhaustion_timeout_ms;
  if (value.max_retries.has_value()) j["max_retries"] = *value.max_retries;
  if (value.side.has_value()) j["side"] = *value.side;
}

inline void from_json(const nlohmann::json& j, AttachListenerParams& value) {
  j.at("queue").get_to(value.queue);
  j.at("port").get_to(value.port);
  if (j.contains("host") && !j["host"].is_null()) {
    value.host = j.at("host").get<std::string>();
  } else {
    value.host = std::nullopt;
  }
  if (j.contains("exhaustion_timeout_ms") && !j["exhaustion_timeout_ms"].is_null()) {
    value.exhaustion_timeout_ms = j.at("exhaustion_timeout_ms").get<std::int64_t>();
  } else {
    value.exhaustion_timeout_ms = std::nullopt;
  }
  if (j.contains("max_retries") && !j["max_retries"].is_null()) {
    value.max_retries = j.at("max_retries").get<std::int64_t>();
  } else {
    value.max_retries = std::nullopt;
  }
  if (j.contains("side") && !j["side"].is_null()) {
    value.side = j.at("side").get<DuplexSide>();
  } else {
    value.side = std::nullopt;
  }
}

struct AttachListenerResult {
  std::string listener_id{};
  std::string queue{};
  std::string status{};
};

inline void to_json(nlohmann::json& j, const AttachListenerResult& value) {
  j = nlohmann::json::object();
  j["listener_id"] = value.listener_id;
  j["queue"] = value.queue;
  j["status"] = value.status;
}

inline void from_json(const nlohmann::json& j, AttachListenerResult& value) {
  j.at("listener_id").get_to(value.listener_id);
  j.at("queue").get_to(value.queue);
  j.at("status").get_to(value.status);
}

struct DetachListenerParams {
  std::string listener_id{};
};

inline void to_json(nlohmann::json& j, const DetachListenerParams& value) {
  j = nlohmann::json::object();
  j["listener_id"] = value.listener_id;
}

inline void from_json(const nlohmann::json& j, DetachListenerParams& value) {
  j.at("listener_id").get_to(value.listener_id);
}

struct DetachListenerResult {
  std::string listener_id{};
  bool detached{};
};

inline void to_json(nlohmann::json& j, const DetachListenerResult& value) {
  j = nlohmann::json::object();
  j["listener_id"] = value.listener_id;
  j["detached"] = value.detached;
}

inline void from_json(const nlohmann::json& j, DetachListenerResult& value) {
  j.at("listener_id").get_to(value.listener_id);
  j.at("detached").get_to(value.detached);
}

struct ListListenersParams {
  std::optional<std::string> queue{};
};

inline void to_json(nlohmann::json& j, const ListListenersParams& value) {
  j = nlohmann::json::object();
  if (value.queue.has_value()) j["queue"] = *value.queue;
}

inline void from_json(const nlohmann::json& j, ListListenersParams& value) {
  if (j.contains("queue") && !j["queue"].is_null()) {
    value.queue = j.at("queue").get<std::string>();
  } else {
    value.queue = std::nullopt;
  }
}

struct ListListenersResult {
  std::vector<Listener> listeners{};
};

inline void to_json(nlohmann::json& j, const ListListenersResult& value) {
  j = nlohmann::json::object();
  j["listeners"] = value.listeners;
}

inline void from_json(const nlohmann::json& j, ListListenersResult& value) {
  j.at("listeners").get_to(value.listeners);
}

struct QueueReadyParams {
  std::string queue{};
};

inline void to_json(nlohmann::json& j, const QueueReadyParams& value) {
  j = nlohmann::json::object();
  j["queue"] = value.queue;
}

inline void from_json(const nlohmann::json& j, QueueReadyParams& value) {
  j.at("queue").get_to(value.queue);
}

struct QueueReadyResult {
  std::string queue{};
  bool ready{};
};

inline void to_json(nlohmann::json& j, const QueueReadyResult& value) {
  j = nlohmann::json::object();
  j["queue"] = value.queue;
  j["ready"] = value.ready;
}

inline void from_json(const nlohmann::json& j, QueueReadyResult& value) {
  j.at("queue").get_to(value.queue);
  j.at("ready").get_to(value.ready);
}

struct ListenerEventParams {
  std::string queue{};
  std::string id{};
  nlohmann::json event{};
};

inline void to_json(nlohmann::json& j, const ListenerEventParams& value) {
  j = nlohmann::json::object();
  j["queue"] = value.queue;
  j["id"] = value.id;
  j["event"] = value.event;
}

inline void from_json(const nlohmann::json& j, ListenerEventParams& value) {
  j.at("queue").get_to(value.queue);
  j.at("id").get_to(value.id);
  j.at("event").get_to(value.event);
}

struct ListenerEventResult {
  Status status{};
};

inline void to_json(nlohmann::json& j, const ListenerEventResult& value) {
  j = nlohmann::json::object();
  j["status"] = value.status;
}

inline void from_json(const nlohmann::json& j, ListenerEventResult& value) {
  j.at("status").get_to(value.status);
}

}  // namespace airbus
