// @generated by scripts/generate_payloads.py — do not edit by hand.
// Source of truth: schema/payloads/*.schema.json
#![allow(clippy::redundant_closure_call)]
#![allow(clippy::needless_lifetimes)]
#![allow(clippy::match_single_binding)]
#![allow(clippy::clone_on_copy)]

#[doc = "`AddParams`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(transparent)]
pub struct AddParams(pub [f64; 2usize]);
impl ::std::ops::Deref for AddParams {
    type Target = [f64; 2usize];
    fn deref(&self) -> &[f64; 2usize] {
        &self.0
    }
}
impl ::std::convert::From<AddParams> for [f64; 2usize] {
    fn from(value: AddParams) -> Self {
        value.0
    }
}
impl ::std::convert::From<[f64; 2usize]> for AddParams {
    fn from(value: [f64; 2usize]) -> Self {
        Self(value)
    }
}
#[doc = "`AddResult`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(transparent)]
pub struct AddResult(pub f64);
impl ::std::ops::Deref for AddResult {
    type Target = f64;
    fn deref(&self) -> &f64 {
        &self.0
    }
}
impl ::std::convert::From<AddResult> for f64 {
    fn from(value: AddResult) -> Self {
        value.0
    }
}
impl ::std::convert::From<f64> for AddResult {
    fn from(value: f64) -> Self {
        Self(value)
    }
}
impl ::std::fmt::Display for AddResult {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        self.0.fmt(f)
    }
}
impl ::std::str::FromStr for AddResult {
    type Err = <f64 as ::std::str::FromStr>::Err;
    fn from_str(value: &str) -> ::std::result::Result<Self, Self::Err> {
        Ok(Self(value.parse()?))
    }
}
impl ::std::convert::TryFrom<&str> for AddResult {
    type Error = <f64 as ::std::str::FromStr>::Err;
    fn try_from(value: &str) -> ::std::result::Result<Self, Self::Error> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<String> for AddResult {
    type Error = <f64 as ::std::str::FromStr>::Err;
    fn try_from(value: String) -> ::std::result::Result<Self, Self::Error> {
        value.parse()
    }
}
#[doc = "`AirbusPayloadRoot`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(untagged)]
pub enum AirbusPayloadRoot {
    QueueName(QueueName),
    EventObject(EventObject),
    PingResult(PingResult),
    AddParams(AddParams),
    AddResult(AddResult),
    PostEventParams(PostEventParams),
    PostEventResult(PostEventResult),
    GetEventsParams(GetEventsParams),
    GetEventsResult(GetEventsResult),
    ListQueuesResult(ListQueuesResult),
    PeekEventsParams(PeekEventsParams),
    PeekEventsResult(PeekEventsResult),
}
impl ::std::convert::From<QueueName> for AirbusPayloadRoot {
    fn from(value: QueueName) -> Self {
        Self::QueueName(value)
    }
}
impl ::std::convert::From<EventObject> for AirbusPayloadRoot {
    fn from(value: EventObject) -> Self {
        Self::EventObject(value)
    }
}
impl ::std::convert::From<PingResult> for AirbusPayloadRoot {
    fn from(value: PingResult) -> Self {
        Self::PingResult(value)
    }
}
impl ::std::convert::From<AddParams> for AirbusPayloadRoot {
    fn from(value: AddParams) -> Self {
        Self::AddParams(value)
    }
}
impl ::std::convert::From<AddResult> for AirbusPayloadRoot {
    fn from(value: AddResult) -> Self {
        Self::AddResult(value)
    }
}
impl ::std::convert::From<PostEventParams> for AirbusPayloadRoot {
    fn from(value: PostEventParams) -> Self {
        Self::PostEventParams(value)
    }
}
impl ::std::convert::From<PostEventResult> for AirbusPayloadRoot {
    fn from(value: PostEventResult) -> Self {
        Self::PostEventResult(value)
    }
}
impl ::std::convert::From<GetEventsParams> for AirbusPayloadRoot {
    fn from(value: GetEventsParams) -> Self {
        Self::GetEventsParams(value)
    }
}
impl ::std::convert::From<GetEventsResult> for AirbusPayloadRoot {
    fn from(value: GetEventsResult) -> Self {
        Self::GetEventsResult(value)
    }
}
impl ::std::convert::From<ListQueuesResult> for AirbusPayloadRoot {
    fn from(value: ListQueuesResult) -> Self {
        Self::ListQueuesResult(value)
    }
}
impl ::std::convert::From<PeekEventsParams> for AirbusPayloadRoot {
    fn from(value: PeekEventsParams) -> Self {
        Self::PeekEventsParams(value)
    }
}
impl ::std::convert::From<PeekEventsResult> for AirbusPayloadRoot {
    fn from(value: PeekEventsResult) -> Self {
        Self::PeekEventsResult(value)
    }
}
#[doc = "`EventObject`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(transparent)]
pub struct EventObject(pub ::serde_json::Map<::std::string::String, ::serde_json::Value>);
impl ::std::ops::Deref for EventObject {
    type Target = ::serde_json::Map<::std::string::String, ::serde_json::Value>;
    fn deref(&self) -> &::serde_json::Map<::std::string::String, ::serde_json::Value> {
        &self.0
    }
}
impl ::std::convert::From<EventObject>
    for ::serde_json::Map<::std::string::String, ::serde_json::Value>
{
    fn from(value: EventObject) -> Self {
        value.0
    }
}
impl ::std::convert::From<::serde_json::Map<::std::string::String, ::serde_json::Value>>
    for EventObject
{
    fn from(value: ::serde_json::Map<::std::string::String, ::serde_json::Value>) -> Self {
        Self(value)
    }
}
#[doc = "`GetEventsParams`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct GetEventsParams {
    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub count: i64,
    pub queue: QueueName,
}
#[doc = "`GetEventsResult`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct GetEventsResult {
    pub events: ::std::vec::Vec<EventObject>,
    pub queue: QueueName,
}
#[doc = "`ListQueuesResult`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct ListQueuesResult {
    pub queues: ::std::vec::Vec<ListQueuesResultQueuesItem>,
}
#[doc = "`ListQueuesResultQueuesItem`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct ListQueuesResultQueuesItem {
    pub depth: u64,
    pub name: QueueName,
}
#[doc = "`PeekEventsParams`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct PeekEventsParams {
    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub count: i64,
    pub queue: QueueName,
}
#[doc = "`PeekEventsResult`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct PeekEventsResult {
    pub events: ::std::vec::Vec<PeekEventsResultEventsItem>,
    pub queue: QueueName,
}
#[doc = "`PeekEventsResultEventsItem`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct PeekEventsResultEventsItem {
    pub event: EventObject,
    pub id: PeekEventsResultEventsItemId,
}
#[doc = "`PeekEventsResultEventsItemId`"]
#[derive(:: serde :: Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct PeekEventsResultEventsItemId(::std::string::String);
impl ::std::ops::Deref for PeekEventsResultEventsItemId {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<PeekEventsResultEventsItemId> for ::std::string::String {
    fn from(value: PeekEventsResultEventsItemId) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for PeekEventsResultEventsItemId {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() < 1usize {
            return Err("shorter than 1 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for PeekEventsResultEventsItemId {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for PeekEventsResultEventsItemId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for PeekEventsResultEventsItemId {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
#[doc = "`PingResult`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
#[serde(transparent)]
pub struct PingResult(pub ::std::string::String);
impl ::std::ops::Deref for PingResult {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<PingResult> for ::std::string::String {
    fn from(value: PingResult) -> Self {
        value.0
    }
}
impl ::std::convert::From<::std::string::String> for PingResult {
    fn from(value: ::std::string::String) -> Self {
        Self(value)
    }
}
impl ::std::fmt::Display for PingResult {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        self.0.fmt(f)
    }
}
impl ::std::str::FromStr for PingResult {
    type Err = ::std::convert::Infallible;
    fn from_str(value: &str) -> ::std::result::Result<Self, Self::Err> {
        Ok(Self(value.to_string()))
    }
}
#[doc = "`PostEventParams`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct PostEventParams {
    pub event: EventObject,
    pub queue: QueueName,
}
#[doc = "`PostEventResult`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct PostEventResult {
    pub id: PostEventResultId,
    pub queue: QueueName,
}
#[doc = "`PostEventResultId`"]
#[derive(:: serde :: Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct PostEventResultId(::std::string::String);
impl ::std::ops::Deref for PostEventResultId {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<PostEventResultId> for ::std::string::String {
    fn from(value: PostEventResultId) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for PostEventResultId {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() < 1usize {
            return Err("shorter than 1 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for PostEventResultId {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for PostEventResultId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for PostEventResultId {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
#[doc = "`QueueName`"]
#[derive(:: serde :: Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct QueueName(::std::string::String);
impl ::std::ops::Deref for QueueName {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<QueueName> for ::std::string::String {
    fn from(value: QueueName) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for QueueName {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() < 1usize {
            return Err("shorter than 1 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for QueueName {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for QueueName {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for QueueName {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
#[doc = " Generation of default values for serde."]
pub mod defaults {
    pub(super) fn default_u64<T, const V: u64>() -> T
    where
        T: ::std::convert::TryFrom<u64>,
        <T as ::std::convert::TryFrom<u64>>::Error: ::std::fmt::Debug,
    {
        T::try_from(V).unwrap()
    }
}
#[doc = " Error types."]
pub mod error {
    #[doc = r" Error from a `TryFrom` or `FromStr` implementation."]
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
