// @generated by scripts/generate_payloads.py — do not edit by hand.
// Source of truth: schema/payloads/*.schema.json
#![allow(clippy::redundant_closure_call)]
#![allow(clippy::needless_lifetimes)]
#![allow(clippy::match_single_binding)]
#![allow(clippy::clone_on_copy)]

#[doc = "`AddParams`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(transparent)]
pub struct AddParams(pub [f64; 2usize]);
impl ::std::ops::Deref for AddParams {
    type Target = [f64; 2usize];
    fn deref(&self) -> &[f64; 2usize] {
        &self.0
    }
}
impl ::std::convert::From<AddParams> for [f64; 2usize] {
    fn from(value: AddParams) -> Self {
        value.0
    }
}
impl ::std::convert::From<[f64; 2usize]> for AddParams {
    fn from(value: [f64; 2usize]) -> Self {
        Self(value)
    }
}
#[doc = "`AddResult`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(transparent)]
pub struct AddResult(pub f64);
impl ::std::ops::Deref for AddResult {
    type Target = f64;
    fn deref(&self) -> &f64 {
        &self.0
    }
}
impl ::std::convert::From<AddResult> for f64 {
    fn from(value: AddResult) -> Self {
        value.0
    }
}
impl ::std::convert::From<f64> for AddResult {
    fn from(value: f64) -> Self {
        Self(value)
    }
}
impl ::std::fmt::Display for AddResult {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        self.0.fmt(f)
    }
}
impl ::std::str::FromStr for AddResult {
    type Err = <f64 as ::std::str::FromStr>::Err;
    fn from_str(value: &str) -> ::std::result::Result<Self, Self::Err> {
        Ok(Self(value.parse()?))
    }
}
impl ::std::convert::TryFrom<&str> for AddResult {
    type Error = <f64 as ::std::str::FromStr>::Err;
    fn try_from(value: &str) -> ::std::result::Result<Self, Self::Error> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<String> for AddResult {
    type Error = <f64 as ::std::str::FromStr>::Err;
    fn try_from(value: String) -> ::std::result::Result<Self, Self::Error> {
        value.parse()
    }
}
#[doc = "`AirbusPayloadRoot`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(untagged)]
pub enum AirbusPayloadRoot {
    QueueName(QueueName),
    EventObject(EventObject),
    QueueMode(QueueMode),
    QueueInfo(QueueInfo),
    DuplexSide(DuplexSide),
    DispatchStrategy(DispatchStrategy),
    PingResult(PingResult),
    AddParams(AddParams),
    AddResult(AddResult),
    PostEventParams(PostEventParams),
    PostEventResult(PostEventResult),
    ListQueuesResult(ListQueuesResult),
    PeekEventsParams(PeekEventsParams),
    PeekEventsResult(PeekEventsResult),
    CreateQueueParams(CreateQueueParams),
    CreateQueueResult(CreateQueueResult),
    AttachListenerParams(AttachListenerParams),
    AttachListenerResult(AttachListenerResult),
    DetachListenerParams(DetachListenerParams),
    DetachListenerResult(DetachListenerResult),
    ListListenersParams(ListListenersParams),
    ListListenersResult(ListListenersResult),
    QueueReadyParams(QueueReadyParams),
    QueueReadyResult(QueueReadyResult),
    ListenerEventParams(ListenerEventParams),
    ListenerEventResult(ListenerEventResult),
}
impl ::std::convert::From<QueueName> for AirbusPayloadRoot {
    fn from(value: QueueName) -> Self {
        Self::QueueName(value)
    }
}
impl ::std::convert::From<EventObject> for AirbusPayloadRoot {
    fn from(value: EventObject) -> Self {
        Self::EventObject(value)
    }
}
impl ::std::convert::From<QueueMode> for AirbusPayloadRoot {
    fn from(value: QueueMode) -> Self {
        Self::QueueMode(value)
    }
}
impl ::std::convert::From<QueueInfo> for AirbusPayloadRoot {
    fn from(value: QueueInfo) -> Self {
        Self::QueueInfo(value)
    }
}
impl ::std::convert::From<DuplexSide> for AirbusPayloadRoot {
    fn from(value: DuplexSide) -> Self {
        Self::DuplexSide(value)
    }
}
impl ::std::convert::From<DispatchStrategy> for AirbusPayloadRoot {
    fn from(value: DispatchStrategy) -> Self {
        Self::DispatchStrategy(value)
    }
}
impl ::std::convert::From<PingResult> for AirbusPayloadRoot {
    fn from(value: PingResult) -> Self {
        Self::PingResult(value)
    }
}
impl ::std::convert::From<AddParams> for AirbusPayloadRoot {
    fn from(value: AddParams) -> Self {
        Self::AddParams(value)
    }
}
impl ::std::convert::From<AddResult> for AirbusPayloadRoot {
    fn from(value: AddResult) -> Self {
        Self::AddResult(value)
    }
}
impl ::std::convert::From<PostEventParams> for AirbusPayloadRoot {
    fn from(value: PostEventParams) -> Self {
        Self::PostEventParams(value)
    }
}
impl ::std::convert::From<PostEventResult> for AirbusPayloadRoot {
    fn from(value: PostEventResult) -> Self {
        Self::PostEventResult(value)
    }
}
impl ::std::convert::From<ListQueuesResult> for AirbusPayloadRoot {
    fn from(value: ListQueuesResult) -> Self {
        Self::ListQueuesResult(value)
    }
}
impl ::std::convert::From<PeekEventsParams> for AirbusPayloadRoot {
    fn from(value: PeekEventsParams) -> Self {
        Self::PeekEventsParams(value)
    }
}
impl ::std::convert::From<PeekEventsResult> for AirbusPayloadRoot {
    fn from(value: PeekEventsResult) -> Self {
        Self::PeekEventsResult(value)
    }
}
impl ::std::convert::From<CreateQueueParams> for AirbusPayloadRoot {
    fn from(value: CreateQueueParams) -> Self {
        Self::CreateQueueParams(value)
    }
}
impl ::std::convert::From<CreateQueueResult> for AirbusPayloadRoot {
    fn from(value: CreateQueueResult) -> Self {
        Self::CreateQueueResult(value)
    }
}
impl ::std::convert::From<AttachListenerParams> for AirbusPayloadRoot {
    fn from(value: AttachListenerParams) -> Self {
        Self::AttachListenerParams(value)
    }
}
impl ::std::convert::From<AttachListenerResult> for AirbusPayloadRoot {
    fn from(value: AttachListenerResult) -> Self {
        Self::AttachListenerResult(value)
    }
}
impl ::std::convert::From<DetachListenerParams> for AirbusPayloadRoot {
    fn from(value: DetachListenerParams) -> Self {
        Self::DetachListenerParams(value)
    }
}
impl ::std::convert::From<DetachListenerResult> for AirbusPayloadRoot {
    fn from(value: DetachListenerResult) -> Self {
        Self::DetachListenerResult(value)
    }
}
impl ::std::convert::From<ListListenersParams> for AirbusPayloadRoot {
    fn from(value: ListListenersParams) -> Self {
        Self::ListListenersParams(value)
    }
}
impl ::std::convert::From<ListListenersResult> for AirbusPayloadRoot {
    fn from(value: ListListenersResult) -> Self {
        Self::ListListenersResult(value)
    }
}
impl ::std::convert::From<QueueReadyParams> for AirbusPayloadRoot {
    fn from(value: QueueReadyParams) -> Self {
        Self::QueueReadyParams(value)
    }
}
impl ::std::convert::From<QueueReadyResult> for AirbusPayloadRoot {
    fn from(value: QueueReadyResult) -> Self {
        Self::QueueReadyResult(value)
    }
}
impl ::std::convert::From<ListenerEventParams> for AirbusPayloadRoot {
    fn from(value: ListenerEventParams) -> Self {
        Self::ListenerEventParams(value)
    }
}
impl ::std::convert::From<ListenerEventResult> for AirbusPayloadRoot {
    fn from(value: ListenerEventResult) -> Self {
        Self::ListenerEventResult(value)
    }
}
#[doc = "`AttachListenerParams`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct AttachListenerParams {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub exhaustion_timeout_ms: ::std::option::Option<u64>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub host: ::std::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub max_retries: ::std::option::Option<u64>,
    pub port: ::std::num::NonZeroU64,
    pub queue: QueueName,
    #[doc = "Listener side for full-duplex queues; required when mode is full-duplex, rejected otherwise"]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub side: ::std::option::Option<DuplexSide>,
}
#[doc = "`AttachListenerResult`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct AttachListenerResult {
    pub listener_id: AttachListenerResultListenerId,
    pub queue: QueueName,
    pub status: ::std::string::String,
}
#[doc = "`AttachListenerResultListenerId`"]
#[derive(:: serde :: Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct AttachListenerResultListenerId(::std::string::String);
impl ::std::ops::Deref for AttachListenerResultListenerId {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<AttachListenerResultListenerId> for ::std::string::String {
    fn from(value: AttachListenerResultListenerId) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for AttachListenerResultListenerId {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() < 1usize {
            return Err("shorter than 1 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for AttachListenerResultListenerId {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for AttachListenerResultListenerId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for AttachListenerResultListenerId {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
#[doc = "`CreateQueueParams`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct CreateQueueParams {
    #[doc = "Fifo only; rejected for broadcast and full-duplex. Default when omitted on fifo: round_robin"]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub dispatch_strategy: ::std::option::Option<DispatchStrategy>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub mode: ::std::option::Option<QueueMode>,
    pub queue: QueueName,
}
#[doc = "`CreateQueueResult`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct CreateQueueResult {
    pub created: bool,
    pub mode: QueueMode,
    pub queue: QueueName,
}
#[doc = "`DetachListenerParams`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct DetachListenerParams {
    pub listener_id: DetachListenerParamsListenerId,
}
#[doc = "`DetachListenerParamsListenerId`"]
#[derive(:: serde :: Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct DetachListenerParamsListenerId(::std::string::String);
impl ::std::ops::Deref for DetachListenerParamsListenerId {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<DetachListenerParamsListenerId> for ::std::string::String {
    fn from(value: DetachListenerParamsListenerId) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for DetachListenerParamsListenerId {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() < 1usize {
            return Err("shorter than 1 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for DetachListenerParamsListenerId {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for DetachListenerParamsListenerId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for DetachListenerParamsListenerId {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
#[doc = "`DetachListenerResult`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct DetachListenerResult {
    pub detached: bool,
    pub listener_id: DetachListenerResultListenerId,
}
#[doc = "`DetachListenerResultListenerId`"]
#[derive(:: serde :: Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct DetachListenerResultListenerId(::std::string::String);
impl ::std::ops::Deref for DetachListenerResultListenerId {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<DetachListenerResultListenerId> for ::std::string::String {
    fn from(value: DetachListenerResultListenerId) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for DetachListenerResultListenerId {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() < 1usize {
            return Err("shorter than 1 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for DetachListenerResultListenerId {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for DetachListenerResultListenerId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for DetachListenerResultListenerId {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
#[doc = "`DispatchStrategy`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum DispatchStrategy {
    #[serde(rename = "round_robin")]
    RoundRobin,
    #[serde(rename = "single_node")]
    SingleNode,
}
impl ::std::fmt::Display for DispatchStrategy {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::RoundRobin => f.write_str("round_robin"),
            Self::SingleNode => f.write_str("single_node"),
        }
    }
}
impl ::std::str::FromStr for DispatchStrategy {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "round_robin" => Ok(Self::RoundRobin),
            "single_node" => Ok(Self::SingleNode),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for DispatchStrategy {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for DispatchStrategy {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`DuplexSide`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum DuplexSide {
    #[serde(rename = "host")]
    Host,
    #[serde(rename = "device")]
    Device,
}
impl ::std::fmt::Display for DuplexSide {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Host => f.write_str("host"),
            Self::Device => f.write_str("device"),
        }
    }
}
impl ::std::str::FromStr for DuplexSide {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "host" => Ok(Self::Host),
            "device" => Ok(Self::Device),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for DuplexSide {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for DuplexSide {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`EventObject`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(transparent)]
pub struct EventObject(pub ::serde_json::Map<::std::string::String, ::serde_json::Value>);
impl ::std::ops::Deref for EventObject {
    type Target = ::serde_json::Map<::std::string::String, ::serde_json::Value>;
    fn deref(&self) -> &::serde_json::Map<::std::string::String, ::serde_json::Value> {
        &self.0
    }
}
impl ::std::convert::From<EventObject>
    for ::serde_json::Map<::std::string::String, ::serde_json::Value>
{
    fn from(value: EventObject) -> Self {
        value.0
    }
}
impl ::std::convert::From<::serde_json::Map<::std::string::String, ::serde_json::Value>>
    for EventObject
{
    fn from(value: ::serde_json::Map<::std::string::String, ::serde_json::Value>) -> Self {
        Self(value)
    }
}
#[doc = "`ListListenersParams`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, Default)]
#[serde(deny_unknown_fields)]
pub struct ListListenersParams {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub queue: ::std::option::Option<QueueName>,
}
#[doc = "`ListListenersResult`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct ListListenersResult {
    pub listeners: ::std::vec::Vec<ListListenersResultListenersItem>,
}
#[doc = "`ListListenersResultListenersItem`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct ListListenersResultListenersItem {
    pub active: bool,
    pub failure_count: u64,
    pub host: ::std::string::String,
    pub id: ListListenersResultListenersItemId,
    pub mode: QueueMode,
    pub port: ::std::num::NonZeroU64,
    pub queue: QueueName,
    #[doc = "Present for full-duplex listeners"]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub side: ::std::option::Option<DuplexSide>,
}
#[doc = "`ListListenersResultListenersItemId`"]
#[derive(:: serde :: Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct ListListenersResultListenersItemId(::std::string::String);
impl ::std::ops::Deref for ListListenersResultListenersItemId {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<ListListenersResultListenersItemId> for ::std::string::String {
    fn from(value: ListListenersResultListenersItemId) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for ListListenersResultListenersItemId {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() < 1usize {
            return Err("shorter than 1 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for ListListenersResultListenersItemId {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for ListListenersResultListenersItemId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for ListListenersResultListenersItemId {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
#[doc = "`ListQueuesResult`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct ListQueuesResult {
    pub queues: ::std::vec::Vec<QueueInfo>,
}
#[doc = "`ListenerEventParams`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct ListenerEventParams {
    pub event: EventObject,
    pub id: ListenerEventParamsId,
    pub queue: QueueName,
}
#[doc = "`ListenerEventParamsId`"]
#[derive(:: serde :: Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct ListenerEventParamsId(::std::string::String);
impl ::std::ops::Deref for ListenerEventParamsId {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<ListenerEventParamsId> for ::std::string::String {
    fn from(value: ListenerEventParamsId) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for ListenerEventParamsId {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() < 1usize {
            return Err("shorter than 1 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for ListenerEventParamsId {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for ListenerEventParamsId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for ListenerEventParamsId {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
#[doc = "`ListenerEventResult`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct ListenerEventResult {
    pub status: ListenerEventResultStatus,
}
#[doc = "`ListenerEventResultStatus`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum ListenerEventResultStatus {
    #[serde(rename = "ok")]
    Ok,
}
impl ::std::fmt::Display for ListenerEventResultStatus {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Ok => f.write_str("ok"),
        }
    }
}
impl ::std::str::FromStr for ListenerEventResultStatus {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "ok" => Ok(Self::Ok),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for ListenerEventResultStatus {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for ListenerEventResultStatus {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`PeekEventsParams`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct PeekEventsParams {
    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub count: i64,
    pub queue: QueueName,
}
#[doc = "`PeekEventsResult`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct PeekEventsResult {
    pub events: ::std::vec::Vec<PeekEventsResultEventsItem>,
    pub queue: QueueName,
}
#[doc = "`PeekEventsResultEventsItem`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct PeekEventsResultEventsItem {
    pub event: EventObject,
    pub id: PeekEventsResultEventsItemId,
}
#[doc = "`PeekEventsResultEventsItemId`"]
#[derive(:: serde :: Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct PeekEventsResultEventsItemId(::std::string::String);
impl ::std::ops::Deref for PeekEventsResultEventsItemId {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<PeekEventsResultEventsItemId> for ::std::string::String {
    fn from(value: PeekEventsResultEventsItemId) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for PeekEventsResultEventsItemId {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() < 1usize {
            return Err("shorter than 1 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for PeekEventsResultEventsItemId {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for PeekEventsResultEventsItemId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for PeekEventsResultEventsItemId {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
#[doc = "`PingResult`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
#[serde(transparent)]
pub struct PingResult(pub ::std::string::String);
impl ::std::ops::Deref for PingResult {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<PingResult> for ::std::string::String {
    fn from(value: PingResult) -> Self {
        value.0
    }
}
impl ::std::convert::From<::std::string::String> for PingResult {
    fn from(value: ::std::string::String) -> Self {
        Self(value)
    }
}
impl ::std::fmt::Display for PingResult {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        self.0.fmt(f)
    }
}
impl ::std::str::FromStr for PingResult {
    type Err = ::std::convert::Infallible;
    fn from_str(value: &str) -> ::std::result::Result<Self, Self::Err> {
        Ok(Self(value.to_string()))
    }
}
#[doc = "`PostEventParams`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct PostEventParams {
    pub event: EventObject,
    pub queue: QueueName,
    #[doc = "Publisher side for full-duplex queues; required when mode is full-duplex, rejected otherwise"]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub side: ::std::option::Option<DuplexSide>,
}
#[doc = "`PostEventResult`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct PostEventResult {
    pub id: PostEventResultId,
    pub queue: QueueName,
}
#[doc = "`PostEventResultId`"]
#[derive(:: serde :: Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct PostEventResultId(::std::string::String);
impl ::std::ops::Deref for PostEventResultId {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<PostEventResultId> for ::std::string::String {
    fn from(value: PostEventResultId) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for PostEventResultId {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() < 1usize {
            return Err("shorter than 1 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for PostEventResultId {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for PostEventResultId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for PostEventResultId {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
#[doc = "`QueueInfo`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct QueueInfo {
    pub depth: u64,
    pub listener_count: u64,
    pub mode: QueueMode,
    pub name: QueueName,
}
#[doc = "`QueueMode`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum QueueMode {
    #[serde(rename = "broadcast")]
    Broadcast,
    #[serde(rename = "fifo")]
    Fifo,
    #[serde(rename = "full-duplex")]
    FullDuplex,
}
impl ::std::fmt::Display for QueueMode {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Broadcast => f.write_str("broadcast"),
            Self::Fifo => f.write_str("fifo"),
            Self::FullDuplex => f.write_str("full-duplex"),
        }
    }
}
impl ::std::str::FromStr for QueueMode {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "broadcast" => Ok(Self::Broadcast),
            "fifo" => Ok(Self::Fifo),
            "full-duplex" => Ok(Self::FullDuplex),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for QueueMode {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for QueueMode {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`QueueName`"]
#[derive(:: serde :: Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct QueueName(::std::string::String);
impl ::std::ops::Deref for QueueName {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<QueueName> for ::std::string::String {
    fn from(value: QueueName) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for QueueName {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() < 1usize {
            return Err("shorter than 1 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for QueueName {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for QueueName {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for QueueName {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
#[doc = "`QueueReadyParams`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct QueueReadyParams {
    pub queue: QueueName,
}
#[doc = "`QueueReadyResult`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct QueueReadyResult {
    pub queue: QueueName,
    #[doc = "Mode-aware readiness: exists for fifo/broadcast; both duplex sides attached for full-duplex"]
    pub ready: bool,
}
#[doc = " Generation of default values for serde."]
pub mod defaults {
    pub(super) fn default_u64<T, const V: u64>() -> T
    where
        T: ::std::convert::TryFrom<u64>,
        <T as ::std::convert::TryFrom<u64>>::Error: ::std::fmt::Debug,
    {
        T::try_from(V).unwrap()
    }
}
#[doc = " Error types."]
pub mod error {
    #[doc = r" Error from a `TryFrom` or `FromStr` implementation."]
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
