# @generated by scripts/generate_payloads.py — do not edit by hand.
# Source of truth: schema/payloads/*.schema.json

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Any

type PingResult = str
type AddResult = float

class QueueMode(StrEnum):
    broadcast = 'broadcast'
    fifo = 'fifo'
    full_duplex = 'full-duplex'


class DispatchStrategy(StrEnum):
    round_robin = 'round_robin'
    single_node = 'single_node'


class DuplexSide(StrEnum):
    host = 'host'
    device = 'device'


@dataclass
class QueueInfo:
    name: str
    depth: int
    mode: QueueMode
    listener_count: int


type AddParams = list[float]


@dataclass
class PostEventParams:
    queue: str
    event: dict[str, Any]
    side: DuplexSide | None = None


@dataclass
class PostEventResult:
    id: str
    queue: str


@dataclass
class ListQueuesResult:
    queues: list[QueueInfo]


@dataclass
class PeekEventsParams:
    queue: str
    count: int | None = 1


@dataclass
class Event:
    id: str
    event: dict[str, Any]


@dataclass
class PeekEventsResult:
    queue: str
    events: list[Event]


@dataclass
class CreateQueueParams:
    queue: str
    mode: QueueMode | None = None
    dispatch_strategy: DispatchStrategy | None = None


@dataclass
class CreateQueueResult:
    queue: str
    mode: QueueMode
    created: bool


@dataclass
class AttachListenerParams:
    queue: str
    port: int
    host: str | None = None
    exhaustion_timeout_ms: int | None = None
    max_retries: int | None = None
    side: DuplexSide | None = None


@dataclass
class AttachListenerResult:
    listener_id: str
    queue: str
    status: str


@dataclass
class DetachListenerParams:
    listener_id: str


@dataclass
class DetachListenerResult:
    listener_id: str
    detached: bool


@dataclass
class ListListenersParams:
    queue: str | None = None


@dataclass
class Listener:
    id: str
    queue: str
    host: str
    port: int
    mode: QueueMode
    failure_count: int
    active: bool
    side: DuplexSide | None = None


@dataclass
class ListListenersResult:
    listeners: list[Listener]


@dataclass
class QueueReadyParams:
    queue: str


@dataclass
class QueueReadyResult:
    queue: str
    ready: bool


@dataclass
class ListenerEventParams:
    queue: str
    id: str
    event: dict[str, Any]


class Status(StrEnum):
    ok = 'ok'


@dataclass
class ListenerEventResult:
    status: Status
