# @generated by scripts/generate_payloads.py — do not edit by hand.
# Source of truth: schema/payloads/*.schema.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

type PingResult = str
type AddResult = float

type AddParams = list[float]


@dataclass
class PostEventParams:
    queue: str
    event: dict[str, Any]


@dataclass
class PostEventResult:
    id: str
    queue: str


@dataclass
class GetEventsParams:
    queue: str
    count: int | None = 1


@dataclass
class GetEventsResult:
    queue: str
    events: list[dict[str, Any]]
