"""Generate C++ payload types and contracts from schema/payloads + openrpc."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Callable

ROOT: Path
PAYLOADS: Path
COMMON_NAME: str
PAYLOAD_FILES: list[str]
CPP_PAYLOADS_OUT: Path
CPP_CONTRACTS_HPP: Path
CPP_CONTRACTS_CPP: Path

load: Callable[[str], dict]
rewrite_refs_rust: Callable[[object], object]


def _cpp_enum_variant(value: str) -> str:
    parts = value.replace("-", "_").split("_")
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def _emit_enum(name: str, values: list[str]) -> str:
    lines = [f"enum class {name} {{"]
    for value in values:
        lines.append(f"  {_cpp_enum_variant(value)},")
    lines.append("};")
    lines.append("")
    lines.append(f"inline void to_json(nlohmann::json& j, {name} value) {{")
    lines.append("  switch (value) {")
    for value in values:
        lines.append(
            f"    case {name}::{_cpp_enum_variant(value)}: j = {json.dumps(value)}; break;"
        )
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append(f"inline void from_json(const nlohmann::json& j, {name}& value) {{")
    lines.append("  const auto& s = j.get_ref<const std::string&>();")
    for value in values:
        lines.append(
            f"  if (s == {json.dumps(value)}) {{ value = {name}::{_cpp_enum_variant(value)}; return; }}"
        )
    lines.append(f'  throw std::invalid_argument("invalid {name}: " + s);')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _emit_struct(name: str, fields: list[tuple[str, str, bool]]) -> str:
    """fields: (json_name, cpp_type, optional)."""
    lines = [f"struct {name} {{"]
    for pname, ctype, _optional in fields:
        lines.append(f"  {ctype} {pname}{{}};")
    lines.append("};")
    lines.append("")
    lines.append(f"inline void to_json(nlohmann::json& j, const {name}& value) {{")
    lines.append("  j = nlohmann::json::object();")
    for pname, _ctype, optional in fields:
        key = json.dumps(pname)
        if optional:
            lines.append(f"  if (value.{pname}.has_value()) j[{key}] = *value.{pname};")
        else:
            lines.append(f"  j[{key}] = value.{pname};")
    lines.append("}")
    lines.append("")
    lines.append(f"inline void from_json(const nlohmann::json& j, {name}& value) {{")
    for pname, ctype, optional in fields:
        key = json.dumps(pname)
        if optional:
            inner = ctype[len("std::optional<") : -1]
            lines.append(f"  if (j.contains({key}) && !j[{key}].is_null()) {{")
            lines.append(f"    value.{pname} = j.at({key}).get<{inner}>();")
            lines.append("  } else {")
            lines.append(f"    value.{pname} = std::nullopt;")
            lines.append("  }")
        else:
            lines.append(f"  j.at({key}).get_to(value.{pname});")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_cpp_payloads() -> None:
    common = load(COMMON_NAME)["$defs"]

    chunks: list[str] = [
        "// @generated by scripts/generate_payloads.py — do not edit by hand.",
        "// Source of truth: schema/payloads/*.schema.json",
        "#pragma once",
        "",
        "#include <cstdint>",
        "#include <optional>",
        "#include <stdexcept>",
        "#include <string>",
        "#include <vector>",
        "",
        "#include <nlohmann/json.hpp>",
        "",
        "namespace airbus {",
        "",
        "using PingResult = std::string;",
        "using AddResult = double;",
        "using AddParams = std::vector<double>;",
        "",
        _emit_enum("QueueMode", list(common["QueueMode"]["enum"])),
        _emit_enum("DispatchStrategy", list(common["DispatchStrategy"]["enum"])),
        _emit_enum("DuplexSide", list(common["DuplexSide"]["enum"])),
        _emit_enum("Status", ["ok"]),
        _emit_struct(
            "QueueInfo",
            [
                ("name", "std::string", False),
                ("depth", "std::int64_t", False),
                ("mode", "QueueMode", False),
                ("listener_count", "std::int64_t", False),
            ],
        ),
        _emit_struct(
            "Event",
            [
                ("id", "std::string", False),
                ("event", "nlohmann::json", False),
            ],
        ),
        _emit_struct(
            "Listener",
            [
                ("id", "std::string", False),
                ("queue", "std::string", False),
                ("host", "std::string", False),
                ("port", "std::int64_t", False),
                ("mode", "QueueMode", False),
                ("failure_count", "std::int64_t", False),
                ("active", "bool", False),
                ("side", "std::optional<DuplexSide>", True),
            ],
        ),
        _emit_struct(
            "PostEventParams",
            [
                ("queue", "std::string", False),
                ("event", "nlohmann::json", False),
                ("side", "std::optional<DuplexSide>", True),
            ],
        ),
        _emit_struct(
            "PostEventResult",
            [
                ("id", "std::string", False),
                ("queue", "std::string", False),
            ],
        ),
        _emit_struct(
            "ListQueuesResult",
            [("queues", "std::vector<QueueInfo>", False)],
        ),
        _emit_struct(
            "PeekEventsParams",
            [
                ("queue", "std::string", False),
                ("count", "std::optional<std::int64_t>", True),
            ],
        ),
        _emit_struct(
            "PeekEventsResult",
            [
                ("queue", "std::string", False),
                ("events", "std::vector<Event>", False),
            ],
        ),
        _emit_struct(
            "CreateQueueParams",
            [
                ("queue", "std::string", False),
                ("mode", "std::optional<QueueMode>", True),
                ("dispatch_strategy", "std::optional<DispatchStrategy>", True),
            ],
        ),
        _emit_struct(
            "CreateQueueResult",
            [
                ("queue", "std::string", False),
                ("mode", "QueueMode", False),
                ("created", "bool", False),
            ],
        ),
        _emit_struct(
            "AttachListenerParams",
            [
                ("queue", "std::string", False),
                ("port", "std::int64_t", False),
                ("host", "std::optional<std::string>", True),
                ("exhaustion_timeout_ms", "std::optional<std::int64_t>", True),
                ("max_retries", "std::optional<std::int64_t>", True),
                ("side", "std::optional<DuplexSide>", True),
            ],
        ),
        _emit_struct(
            "AttachListenerResult",
            [
                ("listener_id", "std::string", False),
                ("queue", "std::string", False),
                ("status", "std::string", False),
            ],
        ),
        _emit_struct(
            "DetachListenerParams",
            [("listener_id", "std::string", False)],
        ),
        _emit_struct(
            "DetachListenerResult",
            [
                ("listener_id", "std::string", False),
                ("detached", "bool", False),
            ],
        ),
        _emit_struct(
            "ListListenersParams",
            [("queue", "std::optional<std::string>", True)],
        ),
        _emit_struct(
            "ListListenersResult",
            [("listeners", "std::vector<Listener>", False)],
        ),
        _emit_struct(
            "QueueReadyParams",
            [("queue", "std::string", False)],
        ),
        _emit_struct(
            "QueueReadyResult",
            [
                ("queue", "std::string", False),
                ("ready", "bool", False),
            ],
        ),
        _emit_struct(
            "ListenerEventParams",
            [
                ("queue", "std::string", False),
                ("id", "std::string", False),
                ("event", "nlohmann::json", False),
            ],
        ),
        _emit_struct(
            "ListenerEventResult",
            [("status", "Status", False)],
        ),
        "}  // namespace airbus",
        "",
    ]

    # Keep schema file list as a freshness anchor (must match openrpc payloads).
    _ = PAYLOAD_FILES

    CPP_PAYLOADS_OUT.parent.mkdir(parents=True, exist_ok=True)
    CPP_PAYLOADS_OUT.write_text("\n".join(chunks))
    try:
        shown = CPP_PAYLOADS_OUT.relative_to(ROOT)
    except ValueError:
        shown = CPP_PAYLOADS_OUT
    print(f"wrote {shown}", flush=True)


def generate_cpp_contracts() -> None:
    schemas: dict[str, Any] = {}
    common = load(COMMON_NAME)["$defs"]
    for filename in PAYLOAD_FILES:
        schema = load(filename)
        schema = rewrite_refs_rust(schema)
        assert isinstance(schema, dict)
        schema["$defs"] = common
        schemas[filename] = schema

    catalog = json.loads((ROOT / "schema" / "openrpc.json").read_text())
    methods: dict[str, Any] = {}
    for method in catalog["methods"]:
        params = method.get("params", [])
        methods[method["name"]] = {
            "params": Path(params[0]["schema"]["$ref"]).name if params else None,
            "params_required": bool(params and params[0].get("required", False)),
            "result": Path(method["result"]["schema"]["$ref"]).name,
            "receiver": method.get("x-receiver", "server"),
        }

    schemas_json = json.dumps(schemas, sort_keys=True)
    methods_json = json.dumps(methods, sort_keys=True)
    if ")AIRBUS(" in schemas_json or ")AIRBUS(" in methods_json:
        raise SystemExit("schema JSON contains raw-string delimiter )AIRBUS(")

    hpp = """\
// @generated by scripts/generate_payloads.py — do not edit by hand.
#pragma once

#include <map>
#include <string>

#include <nlohmann/json.hpp>

namespace airbus {
namespace contracts {

struct MethodInfo {
  std::string params;  // schema filename, empty if none
  bool params_required = false;
  std::string result;
  std::string receiver;
};

const std::map<std::string, nlohmann::json>& schemas();
const std::map<std::string, MethodInfo>& methods();

}  // namespace contracts
}  // namespace airbus
"""

    cpp = f"""\
// @generated by scripts/generate_payloads.py — do not edit by hand.
#include "airbus/contracts.hpp"

namespace airbus {{
namespace contracts {{
namespace {{

const nlohmann::json& schemas_json() {{
  static const nlohmann::json doc = nlohmann::json::parse(R"AIRBUS({schemas_json})AIRBUS");
  return doc;
}}

const nlohmann::json& methods_json() {{
  static const nlohmann::json doc = nlohmann::json::parse(R"AIRBUS({methods_json})AIRBUS");
  return doc;
}}

}}  // namespace

const std::map<std::string, nlohmann::json>& schemas() {{
  static const std::map<std::string, nlohmann::json> value = [] {{
    std::map<std::string, nlohmann::json> out;
    for (auto it = schemas_json().begin(); it != schemas_json().end(); ++it) {{
      out.emplace(it.key(), it.value());
    }}
    return out;
  }}();
  return value;
}}

const std::map<std::string, MethodInfo>& methods() {{
  static const std::map<std::string, MethodInfo> value = [] {{
    std::map<std::string, MethodInfo> out;
    for (auto it = methods_json().begin(); it != methods_json().end(); ++it) {{
      const auto& m = it.value();
      MethodInfo info;
      if (!m.at("params").is_null()) {{
        info.params = m.at("params").get<std::string>();
      }}
      info.params_required = m.at("params_required").get<bool>();
      info.result = m.at("result").get<std::string>();
      info.receiver = m.at("receiver").get<std::string>();
      out.emplace(it.key(), std::move(info));
    }}
    return out;
  }}();
  return value;
}}

}}  // namespace contracts
}}  // namespace airbus
"""

    CPP_CONTRACTS_HPP.parent.mkdir(parents=True, exist_ok=True)
    CPP_CONTRACTS_CPP.parent.mkdir(parents=True, exist_ok=True)
    CPP_CONTRACTS_HPP.write_text(hpp)
    CPP_CONTRACTS_CPP.write_text(cpp)

    def _shown(path: Path) -> Path | str:
        try:
            return path.relative_to(ROOT)
        except ValueError:
            return path

    print(f"wrote {_shown(CPP_CONTRACTS_HPP)}", flush=True)
    print(f"wrote {_shown(CPP_CONTRACTS_CPP)}", flush=True)


def generate_all_cpp() -> None:
    generate_cpp_payloads()
    generate_cpp_contracts()
