// @generated by scripts/generate_payloads.py — do not edit by hand.
// Source of truth: schema/payloads/*.schema.json
#pragma once

#include <Arduino.h>
#include <ArduinoJson.h>
#include <cstdint>
#include <cstring>
#include <utility>
#include <vector>

namespace airbus {

using PingResult = String;
using AddResult = double;

using AddParams = std::vector<double>;

inline bool toJson(JsonVariant dest, const AddParams& value, String& /*err*/) {
  JsonArray arr = dest.to<JsonArray>();
  for (double item : value) arr.add(item);
  return true;
}

inline bool fromJson(JsonVariantConst src, AddParams& value, String& err) {
  JsonArrayConst arr = src.as<JsonArrayConst>();
  if (arr.isNull()) { err = "invalid AddParams"; return false; }
  value.clear();
  for (JsonVariantConst item : arr) value.push_back(item.as<double>());
  return true;
}

inline bool toJson(JsonVariant dest, const String& value, String& /*err*/) {
  dest.set(value);
  return true;
}

inline bool fromJson(JsonVariantConst src, String& value, String& err) {
  if (src.isNull()) { err = "invalid string"; return false; }
  value = src.as<String>();
  return true;
}

inline bool toJson(JsonVariant dest, std::int64_t value, String& /*err*/) {
  dest.set(value);
  return true;
}

inline bool fromJson(JsonVariantConst src, std::int64_t& value, String& err) {
  if (!src.is<std::int64_t>() && !src.is<int>()) { err = "invalid int"; return false; }
  value = src.as<std::int64_t>();
  return true;
}

inline bool toJson(JsonVariant dest, bool value, String& /*err*/) {
  dest.set(value);
  return true;
}

inline bool fromJson(JsonVariantConst src, bool& value, String& err) {
  if (!src.is<bool>()) { err = "invalid bool"; return false; }
  value = src.as<bool>();
  return true;
}

inline bool toJson(JsonVariant dest, double value, String& /*err*/) {
  dest.set(value);
  return true;
}

inline bool fromJson(JsonVariantConst src, double& value, String& err) {
  if (!src.is<double>() && !src.is<int>()) { err = "invalid number"; return false; }
  value = src.as<double>();
  return true;
}

enum class QueueMode {
  Broadcast,
  Fifo,
  FullDuplex,
};

inline bool toJson(JsonVariant dest, QueueMode value, String& /*err*/) {
  switch (value) {
    case QueueMode::Broadcast: dest.set("broadcast"); return true;
    case QueueMode::Fifo: dest.set("fifo"); return true;
    case QueueMode::FullDuplex: dest.set("full-duplex"); return true;
  }
  return false;
}

inline bool fromJson(JsonVariantConst src, QueueMode& value, String& err) {
  const char* s = src.as<const char*>();
  if (s == nullptr) { err = "invalid QueueMode"; return false; }
  if (strcmp(s, "broadcast") == 0) { value = QueueMode::Broadcast; return true; }
  if (strcmp(s, "fifo") == 0) { value = QueueMode::Fifo; return true; }
  if (strcmp(s, "full-duplex") == 0) { value = QueueMode::FullDuplex; return true; }
  err = "invalid QueueMode";
  return false;
}

enum class DuplexSide {
  Host,
  Device,
};

inline bool toJson(JsonVariant dest, DuplexSide value, String& /*err*/) {
  switch (value) {
    case DuplexSide::Host: dest.set("host"); return true;
    case DuplexSide::Device: dest.set("device"); return true;
  }
  return false;
}

inline bool fromJson(JsonVariantConst src, DuplexSide& value, String& err) {
  const char* s = src.as<const char*>();
  if (s == nullptr) { err = "invalid DuplexSide"; return false; }
  if (strcmp(s, "host") == 0) { value = DuplexSide::Host; return true; }
  if (strcmp(s, "device") == 0) { value = DuplexSide::Device; return true; }
  err = "invalid DuplexSide";
  return false;
}

enum class DispatchStrategy {
  RoundRobin,
  SingleNode,
};

inline bool toJson(JsonVariant dest, DispatchStrategy value, String& /*err*/) {
  switch (value) {
    case DispatchStrategy::RoundRobin: dest.set("round_robin"); return true;
    case DispatchStrategy::SingleNode: dest.set("single_node"); return true;
  }
  return false;
}

inline bool fromJson(JsonVariantConst src, DispatchStrategy& value, String& err) {
  const char* s = src.as<const char*>();
  if (s == nullptr) { err = "invalid DispatchStrategy"; return false; }
  if (strcmp(s, "round_robin") == 0) { value = DispatchStrategy::RoundRobin; return true; }
  if (strcmp(s, "single_node") == 0) { value = DispatchStrategy::SingleNode; return true; }
  err = "invalid DispatchStrategy";
  return false;
}

enum class Status {
  Ok,
};

inline bool toJson(JsonVariant dest, Status value, String& /*err*/) {
  switch (value) {
    case Status::Ok: dest.set("ok"); return true;
  }
  return false;
}

inline bool fromJson(JsonVariantConst src, Status& value, String& err) {
  const char* s = src.as<const char*>();
  if (s == nullptr) { err = "invalid Status"; return false; }
  if (strcmp(s, "ok") == 0) { value = Status::Ok; return true; }
  err = "invalid Status";
  return false;
}

struct QueueInfo {
  String name{};
  std::int64_t depth{};
  QueueMode mode{};
  std::int64_t listener_count{};
};

inline bool toJson(JsonObject dest, const QueueInfo& value, String& err) {
  dest["name"] = value.name;
  dest["depth"] = value.depth;
  if (!toJson(dest["mode"], value.mode, err)) return false;
  dest["listener_count"] = value.listener_count;
  return true;
}

inline bool fromJson(JsonObjectConst src, QueueInfo& value, String& err) {
  if (src["name"].isNull()) { err = "missing name"; return false; }
  value.name = src["name"].as<String>();
  if (!src["depth"].is<std::int64_t>() && !src["depth"].is<int>()) { err = "missing depth"; return false; }
  value.depth = src["depth"].as<std::int64_t>();
  if (!fromJson(src["mode"], value.mode, err)) return false;
  if (!src["listener_count"].is<std::int64_t>() && !src["listener_count"].is<int>()) { err = "missing listener_count"; return false; }
  value.listener_count = src["listener_count"].as<std::int64_t>();
  return true;
}

struct PostEventParams {
  String queue{};
  JsonDocument event{};
  bool has_side = false;
  DuplexSide side{};
};

inline bool toJson(JsonObject dest, const PostEventParams& value, String& err) {
  dest["queue"] = value.queue;
  if (!dest["event"].set(value.event.as<JsonVariantConst>())) {
    err = "encode event";
    return false;
  }
  if (value.has_side) {
    if (!toJson(dest["side"], value.side, err)) return false;
  }
  return true;
}

inline bool fromJson(JsonObjectConst src, PostEventParams& value, String& err) {
  if (src["queue"].isNull()) { err = "missing queue"; return false; }
  value.queue = src["queue"].as<String>();
  if (!src["event"].is<JsonObjectConst>() && !src["event"].is<JsonArrayConst>()) {
    err = "missing event";
    return false;
  }
  value.event.clear();
  if (!value.event.set(src["event"])) {
    err = "decode event";
    return false;
  }
  if (src["side"].isNull()) {
    value.has_side = false;
  } else {
    value.has_side = true;
    if (!fromJson(src["side"], value.side, err)) return false;
  }
  return true;
}

struct PostEventResult {
  String id{};
  String queue{};
};

inline bool toJson(JsonObject dest, const PostEventResult& value, String& err) {
  dest["id"] = value.id;
  dest["queue"] = value.queue;
  return true;
}

inline bool fromJson(JsonObjectConst src, PostEventResult& value, String& err) {
  if (src["id"].isNull()) { err = "missing id"; return false; }
  value.id = src["id"].as<String>();
  if (src["queue"].isNull()) { err = "missing queue"; return false; }
  value.queue = src["queue"].as<String>();
  return true;
}

struct ListQueuesResult {
  std::vector<QueueInfo> queues{};
};

inline bool toJson(JsonObject dest, const ListQueuesResult& value, String& err) {
  {
    JsonArray arr = dest["queues"].to<JsonArray>();
    for (const auto& item : value.queues) {
      JsonObject obj = arr.add<JsonObject>();
      if (!toJson(obj, item, err)) return false;
    }
  }
  return true;
}

inline bool fromJson(JsonObjectConst src, ListQueuesResult& value, String& err) {
  {
    JsonArrayConst arr = src["queues"].as<JsonArrayConst>();
    if (arr.isNull()) { err = "missing queues"; return false; }
    value.queues.clear();
    for (JsonVariantConst item : arr) {
      QueueInfo elem{};
      if (!item.is<JsonObjectConst>() || !fromJson(item.as<JsonObjectConst>(), elem, err)) return false;
      value.queues.push_back(std::move(elem));
    }
  }
  return true;
}

struct PeekEventsParams {
  String queue{};
  bool has_count = false;
  std::int64_t count{};
};

inline bool toJson(JsonObject dest, const PeekEventsParams& value, String& err) {
  dest["queue"] = value.queue;
  if (value.has_count) {
    dest["count"] = value.count;
  }
  return true;
}

inline bool fromJson(JsonObjectConst src, PeekEventsParams& value, String& err) {
  if (src["queue"].isNull()) { err = "missing queue"; return false; }
  value.queue = src["queue"].as<String>();
  if (src["count"].isNull()) {
    value.has_count = false;
  } else {
    value.has_count = true;
    value.count = src["count"].as<std::int64_t>();
  }
  return true;
}

struct Event {
  String id{};
  JsonDocument event{};
};

inline bool toJson(JsonObject dest, const Event& value, String& err) {
  dest["id"] = value.id;
  if (!dest["event"].set(value.event.as<JsonVariantConst>())) {
    err = "encode event";
    return false;
  }
  return true;
}

inline bool fromJson(JsonObjectConst src, Event& value, String& err) {
  if (src["id"].isNull()) { err = "missing id"; return false; }
  value.id = src["id"].as<String>();
  if (!src["event"].is<JsonObjectConst>() && !src["event"].is<JsonArrayConst>()) {
    err = "missing event";
    return false;
  }
  value.event.clear();
  if (!value.event.set(src["event"])) {
    err = "decode event";
    return false;
  }
  return true;
}

struct PeekEventsResult {
  String queue{};
  std::vector<Event> events{};
};

inline bool toJson(JsonObject dest, const PeekEventsResult& value, String& err) {
  dest["queue"] = value.queue;
  {
    JsonArray arr = dest["events"].to<JsonArray>();
    for (const auto& item : value.events) {
      JsonObject obj = arr.add<JsonObject>();
      if (!toJson(obj, item, err)) return false;
    }
  }
  return true;
}

inline bool fromJson(JsonObjectConst src, PeekEventsResult& value, String& err) {
  if (src["queue"].isNull()) { err = "missing queue"; return false; }
  value.queue = src["queue"].as<String>();
  {
    JsonArrayConst arr = src["events"].as<JsonArrayConst>();
    if (arr.isNull()) { err = "missing events"; return false; }
    value.events.clear();
    for (JsonVariantConst item : arr) {
      Event elem{};
      if (!item.is<JsonObjectConst>() || !fromJson(item.as<JsonObjectConst>(), elem, err)) return false;
      value.events.push_back(std::move(elem));
    }
  }
  return true;
}

struct CreateQueueParams {
  String queue{};
  bool has_mode = false;
  QueueMode mode{};
  bool has_dispatch_strategy = false;
  DispatchStrategy dispatch_strategy{};
};

inline bool toJson(JsonObject dest, const CreateQueueParams& value, String& err) {
  dest["queue"] = value.queue;
  if (value.has_mode) {
    if (!toJson(dest["mode"], value.mode, err)) return false;
  }
  if (value.has_dispatch_strategy) {
    if (!toJson(dest["dispatch_strategy"], value.dispatch_strategy, err)) return false;
  }
  return true;
}

inline bool fromJson(JsonObjectConst src, CreateQueueParams& value, String& err) {
  if (src["queue"].isNull()) { err = "missing queue"; return false; }
  value.queue = src["queue"].as<String>();
  if (src["mode"].isNull()) {
    value.has_mode = false;
  } else {
    value.has_mode = true;
    if (!fromJson(src["mode"], value.mode, err)) return false;
  }
  if (src["dispatch_strategy"].isNull()) {
    value.has_dispatch_strategy = false;
  } else {
    value.has_dispatch_strategy = true;
    if (!fromJson(src["dispatch_strategy"], value.dispatch_strategy, err)) return false;
  }
  return true;
}

struct CreateQueueResult {
  String queue{};
  QueueMode mode{};
  bool created{};
};

inline bool toJson(JsonObject dest, const CreateQueueResult& value, String& err) {
  dest["queue"] = value.queue;
  if (!toJson(dest["mode"], value.mode, err)) return false;
  dest["created"] = value.created;
  return true;
}

inline bool fromJson(JsonObjectConst src, CreateQueueResult& value, String& err) {
  if (src["queue"].isNull()) { err = "missing queue"; return false; }
  value.queue = src["queue"].as<String>();
  if (!fromJson(src["mode"], value.mode, err)) return false;
  if (!src["created"].is<bool>()) { err = "missing created"; return false; }
  value.created = src["created"].as<bool>();
  return true;
}

struct DeleteQueueParams {
  String queue{};
};

inline bool toJson(JsonObject dest, const DeleteQueueParams& value, String& err) {
  dest["queue"] = value.queue;
  return true;
}

inline bool fromJson(JsonObjectConst src, DeleteQueueParams& value, String& err) {
  if (src["queue"].isNull()) { err = "missing queue"; return false; }
  value.queue = src["queue"].as<String>();
  return true;
}

struct DeleteQueueResult {
  String queue{};
  bool deleted{};
};

inline bool toJson(JsonObject dest, const DeleteQueueResult& value, String& err) {
  dest["queue"] = value.queue;
  dest["deleted"] = value.deleted;
  return true;
}

inline bool fromJson(JsonObjectConst src, DeleteQueueResult& value, String& err) {
  if (src["queue"].isNull()) { err = "missing queue"; return false; }
  value.queue = src["queue"].as<String>();
  if (!src["deleted"].is<bool>()) { err = "missing deleted"; return false; }
  value.deleted = src["deleted"].as<bool>();
  return true;
}

struct AttachListenerParams {
  String queue{};
  std::int64_t port{};
  bool has_host = false;
  String host{};
  bool has_exhaustion_timeout_ms = false;
  std::int64_t exhaustion_timeout_ms{};
  bool has_max_retries = false;
  std::int64_t max_retries{};
  bool has_side = false;
  DuplexSide side{};
};

inline bool toJson(JsonObject dest, const AttachListenerParams& value, String& err) {
  dest["queue"] = value.queue;
  dest["port"] = value.port;
  if (value.has_host) {
    dest["host"] = value.host;
  }
  if (value.has_exhaustion_timeout_ms) {
    dest["exhaustion_timeout_ms"] = value.exhaustion_timeout_ms;
  }
  if (value.has_max_retries) {
    dest["max_retries"] = value.max_retries;
  }
  if (value.has_side) {
    if (!toJson(dest["side"], value.side, err)) return false;
  }
  return true;
}

inline bool fromJson(JsonObjectConst src, AttachListenerParams& value, String& err) {
  if (src["queue"].isNull()) { err = "missing queue"; return false; }
  value.queue = src["queue"].as<String>();
  if (!src["port"].is<std::int64_t>() && !src["port"].is<int>()) { err = "missing port"; return false; }
  value.port = src["port"].as<std::int64_t>();
  if (src["host"].isNull()) {
    value.has_host = false;
  } else {
    value.has_host = true;
    value.host = src["host"].as<String>();
  }
  if (src["exhaustion_timeout_ms"].isNull()) {
    value.has_exhaustion_timeout_ms = false;
  } else {
    value.has_exhaustion_timeout_ms = true;
    value.exhaustion_timeout_ms = src["exhaustion_timeout_ms"].as<std::int64_t>();
  }
  if (src["max_retries"].isNull()) {
    value.has_max_retries = false;
  } else {
    value.has_max_retries = true;
    value.max_retries = src["max_retries"].as<std::int64_t>();
  }
  if (src["side"].isNull()) {
    value.has_side = false;
  } else {
    value.has_side = true;
    if (!fromJson(src["side"], value.side, err)) return false;
  }
  return true;
}

struct AttachListenerResult {
  String listener_id{};
  String queue{};
  String status{};
};

inline bool toJson(JsonObject dest, const AttachListenerResult& value, String& err) {
  dest["listener_id"] = value.listener_id;
  dest["queue"] = value.queue;
  dest["status"] = value.status;
  return true;
}

inline bool fromJson(JsonObjectConst src, AttachListenerResult& value, String& err) {
  if (src["listener_id"].isNull()) { err = "missing listener_id"; return false; }
  value.listener_id = src["listener_id"].as<String>();
  if (src["queue"].isNull()) { err = "missing queue"; return false; }
  value.queue = src["queue"].as<String>();
  if (src["status"].isNull()) { err = "missing status"; return false; }
  value.status = src["status"].as<String>();
  return true;
}

struct DetachListenerParams {
  String listener_id{};
};

inline bool toJson(JsonObject dest, const DetachListenerParams& value, String& err) {
  dest["listener_id"] = value.listener_id;
  return true;
}

inline bool fromJson(JsonObjectConst src, DetachListenerParams& value, String& err) {
  if (src["listener_id"].isNull()) { err = "missing listener_id"; return false; }
  value.listener_id = src["listener_id"].as<String>();
  return true;
}

struct DetachListenerResult {
  String listener_id{};
  bool detached{};
};

inline bool toJson(JsonObject dest, const DetachListenerResult& value, String& err) {
  dest["listener_id"] = value.listener_id;
  dest["detached"] = value.detached;
  return true;
}

inline bool fromJson(JsonObjectConst src, DetachListenerResult& value, String& err) {
  if (src["listener_id"].isNull()) { err = "missing listener_id"; return false; }
  value.listener_id = src["listener_id"].as<String>();
  if (!src["detached"].is<bool>()) { err = "missing detached"; return false; }
  value.detached = src["detached"].as<bool>();
  return true;
}

struct ListListenersParams {
  bool has_queue = false;
  String queue{};
};

inline bool toJson(JsonObject dest, const ListListenersParams& value, String& err) {
  if (value.has_queue) {
    dest["queue"] = value.queue;
  }
  return true;
}

inline bool fromJson(JsonObjectConst src, ListListenersParams& value, String& err) {
  if (src["queue"].isNull()) {
    value.has_queue = false;
  } else {
    value.has_queue = true;
    value.queue = src["queue"].as<String>();
  }
  return true;
}

struct Listener {
  String id{};
  String queue{};
  String host{};
  std::int64_t port{};
  QueueMode mode{};
  std::int64_t failure_count{};
  bool active{};
  bool has_side = false;
  DuplexSide side{};
};

inline bool toJson(JsonObject dest, const Listener& value, String& err) {
  dest["id"] = value.id;
  dest["queue"] = value.queue;
  dest["host"] = value.host;
  dest["port"] = value.port;
  if (!toJson(dest["mode"], value.mode, err)) return false;
  dest["failure_count"] = value.failure_count;
  dest["active"] = value.active;
  if (value.has_side) {
    if (!toJson(dest["side"], value.side, err)) return false;
  }
  return true;
}

inline bool fromJson(JsonObjectConst src, Listener& value, String& err) {
  if (src["id"].isNull()) { err = "missing id"; return false; }
  value.id = src["id"].as<String>();
  if (src["queue"].isNull()) { err = "missing queue"; return false; }
  value.queue = src["queue"].as<String>();
  if (src["host"].isNull()) { err = "missing host"; return false; }
  value.host = src["host"].as<String>();
  if (!src["port"].is<std::int64_t>() && !src["port"].is<int>()) { err = "missing port"; return false; }
  value.port = src["port"].as<std::int64_t>();
  if (!fromJson(src["mode"], value.mode, err)) return false;
  if (!src["failure_count"].is<std::int64_t>() && !src["failure_count"].is<int>()) { err = "missing failure_count"; return false; }
  value.failure_count = src["failure_count"].as<std::int64_t>();
  if (!src["active"].is<bool>()) { err = "missing active"; return false; }
  value.active = src["active"].as<bool>();
  if (src["side"].isNull()) {
    value.has_side = false;
  } else {
    value.has_side = true;
    if (!fromJson(src["side"], value.side, err)) return false;
  }
  return true;
}

struct ListListenersResult {
  std::vector<Listener> listeners{};
};

inline bool toJson(JsonObject dest, const ListListenersResult& value, String& err) {
  {
    JsonArray arr = dest["listeners"].to<JsonArray>();
    for (const auto& item : value.listeners) {
      JsonObject obj = arr.add<JsonObject>();
      if (!toJson(obj, item, err)) return false;
    }
  }
  return true;
}

inline bool fromJson(JsonObjectConst src, ListListenersResult& value, String& err) {
  {
    JsonArrayConst arr = src["listeners"].as<JsonArrayConst>();
    if (arr.isNull()) { err = "missing listeners"; return false; }
    value.listeners.clear();
    for (JsonVariantConst item : arr) {
      Listener elem{};
      if (!item.is<JsonObjectConst>() || !fromJson(item.as<JsonObjectConst>(), elem, err)) return false;
      value.listeners.push_back(std::move(elem));
    }
  }
  return true;
}

struct QueueReadyParams {
  String queue{};
};

inline bool toJson(JsonObject dest, const QueueReadyParams& value, String& err) {
  dest["queue"] = value.queue;
  return true;
}

inline bool fromJson(JsonObjectConst src, QueueReadyParams& value, String& err) {
  if (src["queue"].isNull()) { err = "missing queue"; return false; }
  value.queue = src["queue"].as<String>();
  return true;
}

struct QueueReadyResult {
  String queue{};
  bool ready{};
};

inline bool toJson(JsonObject dest, const QueueReadyResult& value, String& err) {
  dest["queue"] = value.queue;
  dest["ready"] = value.ready;
  return true;
}

inline bool fromJson(JsonObjectConst src, QueueReadyResult& value, String& err) {
  if (src["queue"].isNull()) { err = "missing queue"; return false; }
  value.queue = src["queue"].as<String>();
  if (!src["ready"].is<bool>()) { err = "missing ready"; return false; }
  value.ready = src["ready"].as<bool>();
  return true;
}

struct ListenerEventParams {
  String queue{};
  String id{};
  JsonDocument event{};
};

inline bool toJson(JsonObject dest, const ListenerEventParams& value, String& err) {
  dest["queue"] = value.queue;
  dest["id"] = value.id;
  if (!dest["event"].set(value.event.as<JsonVariantConst>())) {
    err = "encode event";
    return false;
  }
  return true;
}

inline bool fromJson(JsonObjectConst src, ListenerEventParams& value, String& err) {
  if (src["queue"].isNull()) { err = "missing queue"; return false; }
  value.queue = src["queue"].as<String>();
  if (src["id"].isNull()) { err = "missing id"; return false; }
  value.id = src["id"].as<String>();
  if (!src["event"].is<JsonObjectConst>() && !src["event"].is<JsonArrayConst>()) {
    err = "missing event";
    return false;
  }
  value.event.clear();
  if (!value.event.set(src["event"])) {
    err = "decode event";
    return false;
  }
  return true;
}

struct ListenerEventResult {
  Status status{};
};

inline bool toJson(JsonObject dest, const ListenerEventResult& value, String& err) {
  if (!toJson(dest["status"], value.status, err)) return false;
  return true;
}

inline bool fromJson(JsonObjectConst src, ListenerEventResult& value, String& err) {
  if (!fromJson(src["status"], value.status, err)) return false;
  return true;
}

}  // namespace airbus
